project_dir   : '/home/andyb/MutationRates/faststorage/Andrej'
call_set      : '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessed/chimp.raw.filtered.vcf.gz'
resource_set  : '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessed/chimp.known.filtered.vcf.gz'
reference     : '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessed/chimp.pp.ref.fa'
chromosomes   : 'chr1,chr2A,chr2B,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22'
