project_dir: '/home/andyb/MutationRates/faststorage/Andrej'
input_vcf: '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessing/chimp.raw.pure.vcf.gz'
reference: '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessing/chimp.pp.ref.fa'
