project_dir: '/home/andyb/MutationRates/faststorage/Andrej'
input_vcf: '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessed/chimp.raw.filtered.vcf.gz'
reference: '/home/andyb/MutationRates/faststorage/Andrej/data_preprocessed/chimp.pp.ref.fa'
